version: '3.9'

services:
  php:
    image: php:7-fpm
    working_dir: /var/www/app
    volumes:
      - ${APP_PATH}:/var/www/app:cached

  postgres:
    image: postgres:12.6
    restart: always
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    working_dir: /var/www/app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_PATH}:/var/www/app:cached
    links:
      - php

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.8.11-management
    container_name: rabbit-mq
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  default:
    attachable: true
